### PR TITLE
Fixed syntax / cursor target issue: 'App is not defined'

### PR DESCRIPTION
**Pull request by mikepaszkiewicz**
definitely give the example project a run, works for me though - working on supporting scrollTop for overflow: auto conditions

### CODE REVIEW

**Comment by abecks** [comment]
This looks good. Do you think you could change the package name back to the staringatlights namespace and set the version to 0.9.0?

**Comment by mikepaszkiewicz** [comment]
whoops will take care of this tomorrow, meant to switch them back - mike

**Comment by mikepaszkiewicz** [comment]
Just pushed up the Package.describe tweaks.

**Comment by abecks** [comment]
Thanks @mikepaszkiewicz !

**Pull request merged**
